stages:
  split:
    cmd: python3 src/data/data_split.py
    deps:
      - src/data/data_split.py
      - data/raw/raw.csv
    params:
      - split
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  normalize:
    cmd: python3 src/data/normalize.py
    deps:
      - src/data/normalize.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv

  gridsearch:
    cmd: python3 src/models/grid_march.py
    deps:
      - src/models/grid_march.py
      - data/processed/X_train_scaled.csv
    params:
      - gridsearch
    outs:
      - models/best_params.pkl

  training:
    cmd: python3 src/models/training.py
    deps:
      - src/models/training.py
      - models/best_params.pkl
    outs:
      - models/gbr_model.pkl

  evaluate:
    cmd: python3 src/models/evaluate.py
    deps:
      - src/models/evaluate.py
      - models/gbr_model.pkl
    metrics:
      - metrics/scores.json:
          cache: false
    outs:
      - data/prediction.csv
